//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Contracts struct {
	Ticker            string    `sql:"primary_key"`
	ExpirationDate    time.Time `sql:"primary_key"`
	CreatedTimestamp  *time.Time
	Underlying        string
	StrikePrice       float64
	SharesPerContract int32
	OptionType        OptionType
	ExerciseStyle     *ExerciseStyle
}
