//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type ExerciseStyle string

const (
	ExerciseStyle_A ExerciseStyle = "A"
	ExerciseStyle_E ExerciseStyle = "E"
)

var ExerciseStyleAllValues = []ExerciseStyle{
	ExerciseStyle_A,
	ExerciseStyle_E,
}

func (e *ExerciseStyle) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "A":
		*e = ExerciseStyle_A
	case "E":
		*e = ExerciseStyle_E
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for ExerciseStyle enum")
	}

	return nil
}

func (e ExerciseStyle) String() string {
	return string(e)
}
