//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Moneyness string

const (
	Moneyness_I Moneyness = "I"
	Moneyness_A Moneyness = "A"
	Moneyness_O Moneyness = "O"
)

var MoneynessAllValues = []Moneyness{
	Moneyness_I,
	Moneyness_A,
	Moneyness_O,
}

func (e *Moneyness) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "I":
		*e = Moneyness_I
	case "A":
		*e = Moneyness_A
	case "O":
		*e = Moneyness_O
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Moneyness enum")
	}

	return nil
}

func (e Moneyness) String() string {
	return string(e)
}
