//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type OptionType string

const (
	OptionType_Call OptionType = "call"
	OptionType_Put  OptionType = "put"
)

var OptionTypeAllValues = []OptionType{
	OptionType_Call,
	OptionType_Put,
}

func (e *OptionType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "call":
		*e = OptionType_Call
	case "put":
		*e = OptionType_Put
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for OptionType enum")
	}

	return nil
}

func (e OptionType) String() string {
	return string(e)
}
