//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type OptionExercise string

const (
	OptionExercise_Long  OptionExercise = "long"
	OptionExercise_Short OptionExercise = "short"
)

var OptionExerciseAllValues = []OptionExercise{
	OptionExercise_Long,
	OptionExercise_Short,
}

func (e *OptionExercise) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "long":
		*e = OptionExercise_Long
	case "short":
		*e = OptionExercise_Short
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for OptionExercise enum")
	}

	return nil
}

func (e OptionExercise) String() string {
	return string(e)
}
