//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type OptionStyle string

const (
	OptionStyle_American OptionStyle = "american"
	OptionStyle_European OptionStyle = "european"
)

var OptionStyleAllValues = []OptionStyle{
	OptionStyle_American,
	OptionStyle_European,
}

func (e *OptionStyle) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "american":
		*e = OptionStyle_American
	case "european":
		*e = OptionStyle_European
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for OptionStyle enum")
	}

	return nil
}

func (e OptionStyle) String() string {
	return string(e)
}
