//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type OptionMoneyness string

const (
	OptionMoneyness_Itm OptionMoneyness = "ITM"
	OptionMoneyness_Atm OptionMoneyness = "ATM"
	OptionMoneyness_Otm OptionMoneyness = "OTM"
)

var OptionMoneynessAllValues = []OptionMoneyness{
	OptionMoneyness_Itm,
	OptionMoneyness_Atm,
	OptionMoneyness_Otm,
}

func (e *OptionMoneyness) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "ITM":
		*e = OptionMoneyness_Itm
	case "ATM":
		*e = OptionMoneyness_Atm
	case "OTM":
		*e = OptionMoneyness_Otm
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for OptionMoneyness enum")
	}

	return nil
}

func (e OptionMoneyness) String() string {
	return string(e)
}
