//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type OptionPosition string

const (
	OptionPosition_Buy  OptionPosition = "buy"
	OptionPosition_Sell OptionPosition = "sell"
)

var OptionPositionAllValues = []OptionPosition{
	OptionPosition_Buy,
	OptionPosition_Sell,
}

func (e *OptionPosition) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "buy":
		*e = OptionPosition_Buy
	case "sell":
		*e = OptionPosition_Sell
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for OptionPosition enum")
	}

	return nil
}

func (e OptionPosition) String() string {
	return string(e)
}
