//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Snapshots struct {
	Time                  time.Time `sql:"primary_key"`
	Ticker                string    `sql:"primary_key"`
	StrikePrice           float64   `sql:"primary_key"`
	SharesPerContract     int32
	ExpirationDate        time.Time  `sql:"primary_key"`
	OptionType            OptionType `sql:"primary_key"`
	OptionStyle           *OptionStyle
	Underlying            string
	UnderlyingPrice       float64
	UnderlyingLastUpdated *time.Time
	OpenInterest          *float64
	Bid                   float64
	Ask                   float64
	Mid                   float64
	BidSize               float64
	AskSize               float64
	Moneyness             *OptionMoneyness
	Delta                 float64
	Gamma                 float64
	Theta                 float64
	Vega                  float64
	Rho                   *float64
	ImpliedVolatility     *float64
	LastUpdatedSrc        *time.Time
	StartLoadTime         *time.Time
	EndLoadTime           *time.Time
}
