//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SnapshotsOhlc60m struct {
	Bucket                 *time.Time
	Ticker                 *string
	Underlying             *string
	StrikePrice            *float64
	ExpirationDate         *time.Time
	OptionType             *OptionType
	FirstRecordTime        *time.Time
	LastRecordTime         *time.Time
	MoneynessOpen          *Moneyness
	MoneynessClose         *Moneyness
	OpenInterestClose      *float64
	OpenInterestHigh       *float64
	OpenInterestLow        *float64
	OpenInterestOpen       *float64
	ImpliedVolatilityClose *float64
	ImpliedVolatilityHigh  *float64
	ImpliedVolatilityLow   *float64
	ImpliedVolatilityOpen  *float64
	UnderlyingOpen         *float64
	UnderlyingHigh         *float64
	UnderlyingLow          *float64
	UnderlyingClose        *float64
	MidOpen                *float64
	MidHigh                *float64
	MidLow                 *float64
	MidClose               *float64
	BidOpen                *float64
	BidHigh                *float64
	BidLow                 *float64
	BidClose               *float64
	AskOpen                *float64
	AskHigh                *float64
	AskLow                 *float64
	AskClose               *float64
	DeltaOpen              *float64
	DeltaHigh              *float64
	DeltaLow               *float64
	DeltaClose             *float64
	GammaOpen              *float64
	GammaHigh              *float64
	GammaLow               *float64
	GammaClose             *float64
	ThetaOpen              *float64
	ThetaHigh              *float64
	ThetaLow               *float64
	ThetaClose             *float64
	VegaOpen               *float64
	VegaHigh               *float64
	VegaLow                *float64
	VegaClose              *float64
}
