//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var Moneyness = &struct {
	I postgres.StringExpression
	A postgres.StringExpression
	O postgres.StringExpression
}{
	I: postgres.NewEnumValue("I"),
	A: postgres.NewEnumValue("A"),
	O: postgres.NewEnumValue("O"),
}
