//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var OptionType = &struct {
	Call postgres.StringExpression
	Put  postgres.StringExpression
}{
	Call: postgres.NewEnumValue("call"),
	Put:  postgres.NewEnumValue("put"),
}
