//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var OptionMoneyness = &struct {
	Itm postgres.StringExpression
	Atm postgres.StringExpression
	Otm postgres.StringExpression
}{
	Itm: postgres.NewEnumValue("ITM"),
	Atm: postgres.NewEnumValue("ATM"),
	Otm: postgres.NewEnumValue("OTM"),
}
