//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SnapshotsOhlcDailyDetailed = newSnapshotsOhlcDailyDetailedTable("options", "snapshots_ohlc_daily_detailed", "")

type snapshotsOhlcDailyDetailedTable struct {
	postgres.Table

	// Columns
	Bucket                 postgres.ColumnTimestampz
	Ticker                 postgres.ColumnString
	Underlying             postgres.ColumnString
	StrikePrice            postgres.ColumnFloat
	ExpirationDate         postgres.ColumnTimestampz
	OptionType             postgres.ColumnString
	FirstRecordTime        postgres.ColumnTimestampz
	LastRecordTime         postgres.ColumnTimestampz
	MoneynessOpen          postgres.ColumnString
	MoneynessClose         postgres.ColumnString
	OpenInterestClose      postgres.ColumnFloat
	OpenInterestHigh       postgres.ColumnFloat
	OpenInterestLow        postgres.ColumnFloat
	OpenInterestOpen       postgres.ColumnFloat
	ImpliedVolatilityClose postgres.ColumnFloat
	ImpliedVolatilityHigh  postgres.ColumnFloat
	ImpliedVolatilityLow   postgres.ColumnFloat
	ImpliedVolatilityOpen  postgres.ColumnFloat
	UnderlyingOpen         postgres.ColumnFloat
	UnderlyingHigh         postgres.ColumnFloat
	UnderlyingLow          postgres.ColumnFloat
	UnderlyingClose        postgres.ColumnFloat
	MidOpen                postgres.ColumnFloat
	MidHigh                postgres.ColumnFloat
	MidLow                 postgres.ColumnFloat
	MidClose               postgres.ColumnFloat
	BidOpen                postgres.ColumnFloat
	BidHigh                postgres.ColumnFloat
	BidLow                 postgres.ColumnFloat
	BidClose               postgres.ColumnFloat
	AskOpen                postgres.ColumnFloat
	AskHigh                postgres.ColumnFloat
	AskLow                 postgres.ColumnFloat
	AskClose               postgres.ColumnFloat
	DeltaOpen              postgres.ColumnFloat
	DeltaHigh              postgres.ColumnFloat
	DeltaLow               postgres.ColumnFloat
	DeltaClose             postgres.ColumnFloat
	GammaOpen              postgres.ColumnFloat
	GammaHigh              postgres.ColumnFloat
	GammaLow               postgres.ColumnFloat
	GammaClose             postgres.ColumnFloat
	ThetaOpen              postgres.ColumnFloat
	ThetaHigh              postgres.ColumnFloat
	ThetaLow               postgres.ColumnFloat
	ThetaClose             postgres.ColumnFloat
	VegaOpen               postgres.ColumnFloat
	VegaHigh               postgres.ColumnFloat
	VegaLow                postgres.ColumnFloat
	VegaClose              postgres.ColumnFloat
	SharesPerContract      postgres.ColumnInteger
	ExerciseStyle          postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SnapshotsOhlcDailyDetailedTable struct {
	snapshotsOhlcDailyDetailedTable

	EXCLUDED snapshotsOhlcDailyDetailedTable
}

// AS creates new SnapshotsOhlcDailyDetailedTable with assigned alias
func (a SnapshotsOhlcDailyDetailedTable) AS(alias string) *SnapshotsOhlcDailyDetailedTable {
	return newSnapshotsOhlcDailyDetailedTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SnapshotsOhlcDailyDetailedTable with assigned schema name
func (a SnapshotsOhlcDailyDetailedTable) FromSchema(schemaName string) *SnapshotsOhlcDailyDetailedTable {
	return newSnapshotsOhlcDailyDetailedTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SnapshotsOhlcDailyDetailedTable with assigned table prefix
func (a SnapshotsOhlcDailyDetailedTable) WithPrefix(prefix string) *SnapshotsOhlcDailyDetailedTable {
	return newSnapshotsOhlcDailyDetailedTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SnapshotsOhlcDailyDetailedTable with assigned table suffix
func (a SnapshotsOhlcDailyDetailedTable) WithSuffix(suffix string) *SnapshotsOhlcDailyDetailedTable {
	return newSnapshotsOhlcDailyDetailedTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSnapshotsOhlcDailyDetailedTable(schemaName, tableName, alias string) *SnapshotsOhlcDailyDetailedTable {
	return &SnapshotsOhlcDailyDetailedTable{
		snapshotsOhlcDailyDetailedTable: newSnapshotsOhlcDailyDetailedTableImpl(schemaName, tableName, alias),
		EXCLUDED:                        newSnapshotsOhlcDailyDetailedTableImpl("", "excluded", ""),
	}
}

func newSnapshotsOhlcDailyDetailedTableImpl(schemaName, tableName, alias string) snapshotsOhlcDailyDetailedTable {
	var (
		BucketColumn                 = postgres.TimestampzColumn("bucket")
		TickerColumn                 = postgres.StringColumn("ticker")
		UnderlyingColumn             = postgres.StringColumn("underlying")
		StrikePriceColumn            = postgres.FloatColumn("strike_price")
		ExpirationDateColumn         = postgres.TimestampzColumn("expiration_date")
		OptionTypeColumn             = postgres.StringColumn("option_type")
		FirstRecordTimeColumn        = postgres.TimestampzColumn("first_record_time")
		LastRecordTimeColumn         = postgres.TimestampzColumn("last_record_time")
		MoneynessOpenColumn          = postgres.StringColumn("moneyness_open")
		MoneynessCloseColumn         = postgres.StringColumn("moneyness_close")
		OpenInterestCloseColumn      = postgres.FloatColumn("open_interest_close")
		OpenInterestHighColumn       = postgres.FloatColumn("open_interest_high")
		OpenInterestLowColumn        = postgres.FloatColumn("open_interest_low")
		OpenInterestOpenColumn       = postgres.FloatColumn("open_interest_open")
		ImpliedVolatilityCloseColumn = postgres.FloatColumn("implied_volatility_close")
		ImpliedVolatilityHighColumn  = postgres.FloatColumn("implied_volatility_high")
		ImpliedVolatilityLowColumn   = postgres.FloatColumn("implied_volatility_low")
		ImpliedVolatilityOpenColumn  = postgres.FloatColumn("implied_volatility_open")
		UnderlyingOpenColumn         = postgres.FloatColumn("underlying_open")
		UnderlyingHighColumn         = postgres.FloatColumn("underlying_high")
		UnderlyingLowColumn          = postgres.FloatColumn("underlying_low")
		UnderlyingCloseColumn        = postgres.FloatColumn("underlying_close")
		MidOpenColumn                = postgres.FloatColumn("mid_open")
		MidHighColumn                = postgres.FloatColumn("mid_high")
		MidLowColumn                 = postgres.FloatColumn("mid_low")
		MidCloseColumn               = postgres.FloatColumn("mid_close")
		BidOpenColumn                = postgres.FloatColumn("bid_open")
		BidHighColumn                = postgres.FloatColumn("bid_high")
		BidLowColumn                 = postgres.FloatColumn("bid_low")
		BidCloseColumn               = postgres.FloatColumn("bid_close")
		AskOpenColumn                = postgres.FloatColumn("ask_open")
		AskHighColumn                = postgres.FloatColumn("ask_high")
		AskLowColumn                 = postgres.FloatColumn("ask_low")
		AskCloseColumn               = postgres.FloatColumn("ask_close")
		DeltaOpenColumn              = postgres.FloatColumn("delta_open")
		DeltaHighColumn              = postgres.FloatColumn("delta_high")
		DeltaLowColumn               = postgres.FloatColumn("delta_low")
		DeltaCloseColumn             = postgres.FloatColumn("delta_close")
		GammaOpenColumn              = postgres.FloatColumn("gamma_open")
		GammaHighColumn              = postgres.FloatColumn("gamma_high")
		GammaLowColumn               = postgres.FloatColumn("gamma_low")
		GammaCloseColumn             = postgres.FloatColumn("gamma_close")
		ThetaOpenColumn              = postgres.FloatColumn("theta_open")
		ThetaHighColumn              = postgres.FloatColumn("theta_high")
		ThetaLowColumn               = postgres.FloatColumn("theta_low")
		ThetaCloseColumn             = postgres.FloatColumn("theta_close")
		VegaOpenColumn               = postgres.FloatColumn("vega_open")
		VegaHighColumn               = postgres.FloatColumn("vega_high")
		VegaLowColumn                = postgres.FloatColumn("vega_low")
		VegaCloseColumn              = postgres.FloatColumn("vega_close")
		SharesPerContractColumn      = postgres.IntegerColumn("shares_per_contract")
		ExerciseStyleColumn          = postgres.StringColumn("exercise_style")
		allColumns                   = postgres.ColumnList{BucketColumn, TickerColumn, UnderlyingColumn, StrikePriceColumn, ExpirationDateColumn, OptionTypeColumn, FirstRecordTimeColumn, LastRecordTimeColumn, MoneynessOpenColumn, MoneynessCloseColumn, OpenInterestCloseColumn, OpenInterestHighColumn, OpenInterestLowColumn, OpenInterestOpenColumn, ImpliedVolatilityCloseColumn, ImpliedVolatilityHighColumn, ImpliedVolatilityLowColumn, ImpliedVolatilityOpenColumn, UnderlyingOpenColumn, UnderlyingHighColumn, UnderlyingLowColumn, UnderlyingCloseColumn, MidOpenColumn, MidHighColumn, MidLowColumn, MidCloseColumn, BidOpenColumn, BidHighColumn, BidLowColumn, BidCloseColumn, AskOpenColumn, AskHighColumn, AskLowColumn, AskCloseColumn, DeltaOpenColumn, DeltaHighColumn, DeltaLowColumn, DeltaCloseColumn, GammaOpenColumn, GammaHighColumn, GammaLowColumn, GammaCloseColumn, ThetaOpenColumn, ThetaHighColumn, ThetaLowColumn, ThetaCloseColumn, VegaOpenColumn, VegaHighColumn, VegaLowColumn, VegaCloseColumn, SharesPerContractColumn, ExerciseStyleColumn}
		mutableColumns               = postgres.ColumnList{BucketColumn, TickerColumn, UnderlyingColumn, StrikePriceColumn, ExpirationDateColumn, OptionTypeColumn, FirstRecordTimeColumn, LastRecordTimeColumn, MoneynessOpenColumn, MoneynessCloseColumn, OpenInterestCloseColumn, OpenInterestHighColumn, OpenInterestLowColumn, OpenInterestOpenColumn, ImpliedVolatilityCloseColumn, ImpliedVolatilityHighColumn, ImpliedVolatilityLowColumn, ImpliedVolatilityOpenColumn, UnderlyingOpenColumn, UnderlyingHighColumn, UnderlyingLowColumn, UnderlyingCloseColumn, MidOpenColumn, MidHighColumn, MidLowColumn, MidCloseColumn, BidOpenColumn, BidHighColumn, BidLowColumn, BidCloseColumn, AskOpenColumn, AskHighColumn, AskLowColumn, AskCloseColumn, DeltaOpenColumn, DeltaHighColumn, DeltaLowColumn, DeltaCloseColumn, GammaOpenColumn, GammaHighColumn, GammaLowColumn, GammaCloseColumn, ThetaOpenColumn, ThetaHighColumn, ThetaLowColumn, ThetaCloseColumn, VegaOpenColumn, VegaHighColumn, VegaLowColumn, VegaCloseColumn, SharesPerContractColumn, ExerciseStyleColumn}
		defaultColumns               = postgres.ColumnList{}
	)

	return snapshotsOhlcDailyDetailedTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Bucket:                 BucketColumn,
		Ticker:                 TickerColumn,
		Underlying:             UnderlyingColumn,
		StrikePrice:            StrikePriceColumn,
		ExpirationDate:         ExpirationDateColumn,
		OptionType:             OptionTypeColumn,
		FirstRecordTime:        FirstRecordTimeColumn,
		LastRecordTime:         LastRecordTimeColumn,
		MoneynessOpen:          MoneynessOpenColumn,
		MoneynessClose:         MoneynessCloseColumn,
		OpenInterestClose:      OpenInterestCloseColumn,
		OpenInterestHigh:       OpenInterestHighColumn,
		OpenInterestLow:        OpenInterestLowColumn,
		OpenInterestOpen:       OpenInterestOpenColumn,
		ImpliedVolatilityClose: ImpliedVolatilityCloseColumn,
		ImpliedVolatilityHigh:  ImpliedVolatilityHighColumn,
		ImpliedVolatilityLow:   ImpliedVolatilityLowColumn,
		ImpliedVolatilityOpen:  ImpliedVolatilityOpenColumn,
		UnderlyingOpen:         UnderlyingOpenColumn,
		UnderlyingHigh:         UnderlyingHighColumn,
		UnderlyingLow:          UnderlyingLowColumn,
		UnderlyingClose:        UnderlyingCloseColumn,
		MidOpen:                MidOpenColumn,
		MidHigh:                MidHighColumn,
		MidLow:                 MidLowColumn,
		MidClose:               MidCloseColumn,
		BidOpen:                BidOpenColumn,
		BidHigh:                BidHighColumn,
		BidLow:                 BidLowColumn,
		BidClose:               BidCloseColumn,
		AskOpen:                AskOpenColumn,
		AskHigh:                AskHighColumn,
		AskLow:                 AskLowColumn,
		AskClose:               AskCloseColumn,
		DeltaOpen:              DeltaOpenColumn,
		DeltaHigh:              DeltaHighColumn,
		DeltaLow:               DeltaLowColumn,
		DeltaClose:             DeltaCloseColumn,
		GammaOpen:              GammaOpenColumn,
		GammaHigh:              GammaHighColumn,
		GammaLow:               GammaLowColumn,
		GammaClose:             GammaCloseColumn,
		ThetaOpen:              ThetaOpenColumn,
		ThetaHigh:              ThetaHighColumn,
		ThetaLow:               ThetaLowColumn,
		ThetaClose:             ThetaCloseColumn,
		VegaOpen:               VegaOpenColumn,
		VegaHigh:               VegaHighColumn,
		VegaLow:                VegaLowColumn,
		VegaClose:              VegaCloseColumn,
		SharesPerContract:      SharesPerContractColumn,
		ExerciseStyle:          ExerciseStyleColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
