//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Contracts = newContractsTable("options", "contracts", "")

type contractsTable struct {
	postgres.Table

	// Columns
	Ticker            postgres.ColumnString
	ExpirationDate    postgres.ColumnTimestampz
	CreatedTimestamp  postgres.ColumnTimestampz
	Underlying        postgres.ColumnString
	StrikePrice       postgres.ColumnFloat
	SharesPerContract postgres.ColumnInteger
	OptionType        postgres.ColumnString
	ExerciseStyle     postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ContractsTable struct {
	contractsTable

	EXCLUDED contractsTable
}

// AS creates new ContractsTable with assigned alias
func (a ContractsTable) AS(alias string) *ContractsTable {
	return newContractsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ContractsTable with assigned schema name
func (a ContractsTable) FromSchema(schemaName string) *ContractsTable {
	return newContractsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ContractsTable with assigned table prefix
func (a ContractsTable) WithPrefix(prefix string) *ContractsTable {
	return newContractsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ContractsTable with assigned table suffix
func (a ContractsTable) WithSuffix(suffix string) *ContractsTable {
	return newContractsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newContractsTable(schemaName, tableName, alias string) *ContractsTable {
	return &ContractsTable{
		contractsTable: newContractsTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newContractsTableImpl("", "excluded", ""),
	}
}

func newContractsTableImpl(schemaName, tableName, alias string) contractsTable {
	var (
		TickerColumn            = postgres.StringColumn("ticker")
		ExpirationDateColumn    = postgres.TimestampzColumn("expiration_date")
		CreatedTimestampColumn  = postgres.TimestampzColumn("created_timestamp")
		UnderlyingColumn        = postgres.StringColumn("underlying")
		StrikePriceColumn       = postgres.FloatColumn("strike_price")
		SharesPerContractColumn = postgres.IntegerColumn("shares_per_contract")
		OptionTypeColumn        = postgres.StringColumn("option_type")
		ExerciseStyleColumn     = postgres.StringColumn("exercise_style")
		allColumns              = postgres.ColumnList{TickerColumn, ExpirationDateColumn, CreatedTimestampColumn, UnderlyingColumn, StrikePriceColumn, SharesPerContractColumn, OptionTypeColumn, ExerciseStyleColumn}
		mutableColumns          = postgres.ColumnList{CreatedTimestampColumn, UnderlyingColumn, StrikePriceColumn, SharesPerContractColumn, OptionTypeColumn, ExerciseStyleColumn}
		defaultColumns          = postgres.ColumnList{CreatedTimestampColumn, ExerciseStyleColumn}
	)

	return contractsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Ticker:            TickerColumn,
		ExpirationDate:    ExpirationDateColumn,
		CreatedTimestamp:  CreatedTimestampColumn,
		Underlying:        UnderlyingColumn,
		StrikePrice:       StrikePriceColumn,
		SharesPerContract: SharesPerContractColumn,
		OptionType:        OptionTypeColumn,
		ExerciseStyle:     ExerciseStyleColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
