//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Snapshots = newSnapshotsTable("options", "snapshots", "")

type snapshotsTable struct {
	postgres.Table

	// Columns
	Time                  postgres.ColumnTimestampz
	Ticker                postgres.ColumnString
	StrikePrice           postgres.ColumnFloat
	SharesPerContract     postgres.ColumnInteger
	ExpirationDate        postgres.ColumnDate
	OptionType            postgres.ColumnString
	OptionStyle           postgres.ColumnString
	Underlying            postgres.ColumnString
	UnderlyingPrice       postgres.ColumnFloat
	UnderlyingLastUpdated postgres.ColumnTimestampz
	Volume                postgres.ColumnInteger
	OpenInterest          postgres.ColumnInteger
	Bid                   postgres.ColumnFloat
	Ask                   postgres.ColumnFloat
	BidSize               postgres.ColumnInteger
	AskSize               postgres.ColumnInteger
	Delta                 postgres.ColumnFloat
	Gamma                 postgres.ColumnFloat
	Theta                 postgres.ColumnFloat
	Vega                  postgres.ColumnFloat
	Rho                   postgres.ColumnFloat
	ImpliedVolatility     postgres.ColumnFloat
	LastUpdatedSrc        postgres.ColumnTimestampz
	StartLoadTime         postgres.ColumnTimestampz
	EndLoadTime           postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SnapshotsTable struct {
	snapshotsTable

	EXCLUDED snapshotsTable
}

// AS creates new SnapshotsTable with assigned alias
func (a SnapshotsTable) AS(alias string) *SnapshotsTable {
	return newSnapshotsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SnapshotsTable with assigned schema name
func (a SnapshotsTable) FromSchema(schemaName string) *SnapshotsTable {
	return newSnapshotsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SnapshotsTable with assigned table prefix
func (a SnapshotsTable) WithPrefix(prefix string) *SnapshotsTable {
	return newSnapshotsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SnapshotsTable with assigned table suffix
func (a SnapshotsTable) WithSuffix(suffix string) *SnapshotsTable {
	return newSnapshotsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSnapshotsTable(schemaName, tableName, alias string) *SnapshotsTable {
	return &SnapshotsTable{
		snapshotsTable: newSnapshotsTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newSnapshotsTableImpl("", "excluded", ""),
	}
}

func newSnapshotsTableImpl(schemaName, tableName, alias string) snapshotsTable {
	var (
		TimeColumn                  = postgres.TimestampzColumn("time")
		TickerColumn                = postgres.StringColumn("ticker")
		StrikePriceColumn           = postgres.FloatColumn("strike_price")
		SharesPerContractColumn     = postgres.IntegerColumn("shares_per_contract")
		ExpirationDateColumn        = postgres.DateColumn("expiration_date")
		OptionTypeColumn            = postgres.StringColumn("option_type")
		OptionStyleColumn           = postgres.StringColumn("option_style")
		UnderlyingColumn            = postgres.StringColumn("underlying")
		UnderlyingPriceColumn       = postgres.FloatColumn("underlying_price")
		UnderlyingLastUpdatedColumn = postgres.TimestampzColumn("underlying_last_updated")
		VolumeColumn                = postgres.IntegerColumn("volume")
		OpenInterestColumn          = postgres.IntegerColumn("open_interest")
		BidColumn                   = postgres.FloatColumn("bid")
		AskColumn                   = postgres.FloatColumn("ask")
		BidSizeColumn               = postgres.IntegerColumn("bid_size")
		AskSizeColumn               = postgres.IntegerColumn("ask_size")
		DeltaColumn                 = postgres.FloatColumn("delta")
		GammaColumn                 = postgres.FloatColumn("gamma")
		ThetaColumn                 = postgres.FloatColumn("theta")
		VegaColumn                  = postgres.FloatColumn("vega")
		RhoColumn                   = postgres.FloatColumn("rho")
		ImpliedVolatilityColumn     = postgres.FloatColumn("implied_volatility")
		LastUpdatedSrcColumn        = postgres.TimestampzColumn("last_updated_src")
		StartLoadTimeColumn         = postgres.TimestampzColumn("start_load_time")
		EndLoadTimeColumn           = postgres.TimestampzColumn("end_load_time")
		allColumns                  = postgres.ColumnList{TimeColumn, TickerColumn, StrikePriceColumn, SharesPerContractColumn, ExpirationDateColumn, OptionTypeColumn, OptionStyleColumn, UnderlyingColumn, UnderlyingPriceColumn, UnderlyingLastUpdatedColumn, VolumeColumn, OpenInterestColumn, BidColumn, AskColumn, BidSizeColumn, AskSizeColumn, DeltaColumn, GammaColumn, ThetaColumn, VegaColumn, RhoColumn, ImpliedVolatilityColumn, LastUpdatedSrcColumn, StartLoadTimeColumn, EndLoadTimeColumn}
		mutableColumns              = postgres.ColumnList{SharesPerContractColumn, OptionStyleColumn, UnderlyingColumn, UnderlyingPriceColumn, UnderlyingLastUpdatedColumn, VolumeColumn, OpenInterestColumn, BidColumn, AskColumn, BidSizeColumn, AskSizeColumn, DeltaColumn, GammaColumn, ThetaColumn, VegaColumn, RhoColumn, ImpliedVolatilityColumn, LastUpdatedSrcColumn, StartLoadTimeColumn, EndLoadTimeColumn}
		defaultColumns              = postgres.ColumnList{TimeColumn, OptionStyleColumn, RhoColumn}
	)

	return snapshotsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Time:                  TimeColumn,
		Ticker:                TickerColumn,
		StrikePrice:           StrikePriceColumn,
		SharesPerContract:     SharesPerContractColumn,
		ExpirationDate:        ExpirationDateColumn,
		OptionType:            OptionTypeColumn,
		OptionStyle:           OptionStyleColumn,
		Underlying:            UnderlyingColumn,
		UnderlyingPrice:       UnderlyingPriceColumn,
		UnderlyingLastUpdated: UnderlyingLastUpdatedColumn,
		Volume:                VolumeColumn,
		OpenInterest:          OpenInterestColumn,
		Bid:                   BidColumn,
		Ask:                   AskColumn,
		BidSize:               BidSizeColumn,
		AskSize:               AskSizeColumn,
		Delta:                 DeltaColumn,
		Gamma:                 GammaColumn,
		Theta:                 ThetaColumn,
		Vega:                  VegaColumn,
		Rho:                   RhoColumn,
		ImpliedVolatility:     ImpliedVolatilityColumn,
		LastUpdatedSrc:        LastUpdatedSrcColumn,
		StartLoadTime:         StartLoadTimeColumn,
		EndLoadTime:           EndLoadTimeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
