//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Snapshots = newSnapshotsTable("options", "snapshots", "")

type snapshotsTable struct {
	postgres.Table

	// Columns
	Timestamp             postgres.ColumnTimestampz
	Ticker                postgres.ColumnString
	Underlying            postgres.ColumnString
	StrikePrice           postgres.ColumnFloat
	ExpirationDate        postgres.ColumnTimestampz
	OptionType            postgres.ColumnString
	DataSrc               postgres.ColumnString
	UnderlyingPrice       postgres.ColumnFloat
	UnderlyingLastUpdated postgres.ColumnTimestampz
	OpenInterest          postgres.ColumnFloat
	Bid                   postgres.ColumnFloat
	Ask                   postgres.ColumnFloat
	Midpoint              postgres.ColumnFloat
	BidSize               postgres.ColumnFloat
	AskSize               postgres.ColumnFloat
	IntrinsicValue        postgres.ColumnFloat
	Moneyness             postgres.ColumnString
	Delta                 postgres.ColumnFloat
	Gamma                 postgres.ColumnFloat
	Theta                 postgres.ColumnFloat
	Vega                  postgres.ColumnFloat
	Rho                   postgres.ColumnFloat
	ImpliedVolatility     postgres.ColumnFloat
	LastUpdatedSrc        postgres.ColumnTimestampz
	StartLoadTime         postgres.ColumnTimestampz
	EndLoadTime           postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SnapshotsTable struct {
	snapshotsTable

	EXCLUDED snapshotsTable
}

// AS creates new SnapshotsTable with assigned alias
func (a SnapshotsTable) AS(alias string) *SnapshotsTable {
	return newSnapshotsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SnapshotsTable with assigned schema name
func (a SnapshotsTable) FromSchema(schemaName string) *SnapshotsTable {
	return newSnapshotsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SnapshotsTable with assigned table prefix
func (a SnapshotsTable) WithPrefix(prefix string) *SnapshotsTable {
	return newSnapshotsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SnapshotsTable with assigned table suffix
func (a SnapshotsTable) WithSuffix(suffix string) *SnapshotsTable {
	return newSnapshotsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSnapshotsTable(schemaName, tableName, alias string) *SnapshotsTable {
	return &SnapshotsTable{
		snapshotsTable: newSnapshotsTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newSnapshotsTableImpl("", "excluded", ""),
	}
}

func newSnapshotsTableImpl(schemaName, tableName, alias string) snapshotsTable {
	var (
		TimestampColumn             = postgres.TimestampzColumn("timestamp")
		TickerColumn                = postgres.StringColumn("ticker")
		UnderlyingColumn            = postgres.StringColumn("underlying")
		StrikePriceColumn           = postgres.FloatColumn("strike_price")
		ExpirationDateColumn        = postgres.TimestampzColumn("expiration_date")
		OptionTypeColumn            = postgres.StringColumn("option_type")
		DataSrcColumn               = postgres.StringColumn("data_src")
		UnderlyingPriceColumn       = postgres.FloatColumn("underlying_price")
		UnderlyingLastUpdatedColumn = postgres.TimestampzColumn("underlying_last_updated")
		OpenInterestColumn          = postgres.FloatColumn("open_interest")
		BidColumn                   = postgres.FloatColumn("bid")
		AskColumn                   = postgres.FloatColumn("ask")
		MidpointColumn              = postgres.FloatColumn("midpoint")
		BidSizeColumn               = postgres.FloatColumn("bid_size")
		AskSizeColumn               = postgres.FloatColumn("ask_size")
		IntrinsicValueColumn        = postgres.FloatColumn("intrinsic_value")
		MoneynessColumn             = postgres.StringColumn("moneyness")
		DeltaColumn                 = postgres.FloatColumn("delta")
		GammaColumn                 = postgres.FloatColumn("gamma")
		ThetaColumn                 = postgres.FloatColumn("theta")
		VegaColumn                  = postgres.FloatColumn("vega")
		RhoColumn                   = postgres.FloatColumn("rho")
		ImpliedVolatilityColumn     = postgres.FloatColumn("implied_volatility")
		LastUpdatedSrcColumn        = postgres.TimestampzColumn("last_updated_src")
		StartLoadTimeColumn         = postgres.TimestampzColumn("start_load_time")
		EndLoadTimeColumn           = postgres.TimestampzColumn("end_load_time")
		allColumns                  = postgres.ColumnList{TimestampColumn, TickerColumn, UnderlyingColumn, StrikePriceColumn, ExpirationDateColumn, OptionTypeColumn, DataSrcColumn, UnderlyingPriceColumn, UnderlyingLastUpdatedColumn, OpenInterestColumn, BidColumn, AskColumn, MidpointColumn, BidSizeColumn, AskSizeColumn, IntrinsicValueColumn, MoneynessColumn, DeltaColumn, GammaColumn, ThetaColumn, VegaColumn, RhoColumn, ImpliedVolatilityColumn, LastUpdatedSrcColumn, StartLoadTimeColumn, EndLoadTimeColumn}
		mutableColumns              = postgres.ColumnList{UnderlyingColumn, StrikePriceColumn, ExpirationDateColumn, OptionTypeColumn, DataSrcColumn, UnderlyingPriceColumn, UnderlyingLastUpdatedColumn, OpenInterestColumn, BidColumn, AskColumn, BidSizeColumn, AskSizeColumn, DeltaColumn, GammaColumn, ThetaColumn, VegaColumn, RhoColumn, ImpliedVolatilityColumn, LastUpdatedSrcColumn, StartLoadTimeColumn, EndLoadTimeColumn}
		defaultColumns              = postgres.ColumnList{OpenInterestColumn, MidpointColumn, IntrinsicValueColumn, MoneynessColumn, RhoColumn}
	)

	return snapshotsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Timestamp:             TimestampColumn,
		Ticker:                TickerColumn,
		Underlying:            UnderlyingColumn,
		StrikePrice:           StrikePriceColumn,
		ExpirationDate:        ExpirationDateColumn,
		OptionType:            OptionTypeColumn,
		DataSrc:               DataSrcColumn,
		UnderlyingPrice:       UnderlyingPriceColumn,
		UnderlyingLastUpdated: UnderlyingLastUpdatedColumn,
		OpenInterest:          OpenInterestColumn,
		Bid:                   BidColumn,
		Ask:                   AskColumn,
		Midpoint:              MidpointColumn,
		BidSize:               BidSizeColumn,
		AskSize:               AskSizeColumn,
		IntrinsicValue:        IntrinsicValueColumn,
		Moneyness:             MoneynessColumn,
		Delta:                 DeltaColumn,
		Gamma:                 GammaColumn,
		Theta:                 ThetaColumn,
		Vega:                  VegaColumn,
		Rho:                   RhoColumn,
		ImpliedVolatility:     ImpliedVolatilityColumn,
		LastUpdatedSrc:        LastUpdatedSrcColumn,
		StartLoadTime:         StartLoadTimeColumn,
		EndLoadTime:           EndLoadTimeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
